### PR TITLE
Add diagrams for all playground sources

### PR DESCRIPTION
**Pull request by rebeccabilbro**
This PR resolves sc-19395, which proposed that we create a consistent way to diagram sample event-driven architectures for projects that could theoretically be done using the playground data source and Ensign.

### CODE REVIEW

**Review by Aatmaj1 — APPROVED** [review]
@rebeccabilbro it looks good 👍 and very simple to understand. Just a suggestion should we include any details in data playground regarding what publisher or subscriber means?

**Comment by rebeccabilbro** [comment]
> @rebeccabilbro it looks good 👍 and very simple to understand. Just a suggestion should we include any details in data playground regarding what publisher or subscriber means?

Thanks @Aatmaj1! What details would you recommend?

**Comment by Aatmaj1** [comment]
> > @rebeccabilbro it looks good 👍 and very simple to understand. Just a suggestion should we include any details in data playground regarding what publisher or subscriber means?
> 
> Thanks @Aatmaj1! What details would you recommend?

@rebeccabilbro just a thought -> If I go to our website's data playground, I can see the examples, and if I look at the flowchart, I can see the words "ensign publisher" and "ensign subscriber," so I was wondering if we could include a diagram on the main page of the playground indicating that ensign consists of two parts—a publisher and a subscriber—and outlining the roles of each.

**Comment by rebeccabilbro** [comment]
> > > @rebeccabilbro it looks good 👍 and very simple to understand. Just a suggestion should we include any details in data playground regarding what publisher or subscriber means?
> > 
> > 
> > Thanks @Aatmaj1! What details would you recommend?
> 
> @rebeccabilbro just a thought -> If I go to our website's data playground, I can see the examples, and if I look at the flowchart, I can see the words "ensign publisher" and "ensign subscriber," so I was wondering if we could include a diagram on the main page of the playground indicating that ensign consists of two parts—a publisher and a subscriber—and outlining the roles of each.

Interesting idea! Your original diagram also referenced `Publishers` and `Subscribers`, which is part of why I included them in mine &mdash; it does seem like it's important for us to show the role that Ensign is playing in the architecture.  However, as you have already seen, most things that interact with Ensign from a client perspective are more like `Handlers`, which can contain >= 0 `Publishers` and  >= 0 `Subscribers`, so it would be misleading and confusing to say that Ensign consists only of `Publishers` and `Subscribers`.  I will spend some more time thinking about this so that we can produce documentation that is helpful and clear. Could you create a follow-on story for me to think about this a bit more next week?

**Pull request merged**
