### PR TITLE
add Chinese menu homepage and i18n file

### PR DESCRIPTION
**Pull request by KNGJOEL**

### CODE REVIEW

**Review by rebeccabilbro — CHANGES_REQUESTED** [review]
I believe it is preferred to use the 2 letter code `zh` for Chinese-language content rather than `cn` &mdash; @tl6kk can you confirm?

**Comment by rebeccabilbro** [comment]
Just want to confirm @KNGJOEL  &mdash; is this is all I should see for this PR?

Screen Shot 2021-08-10 at 5 58 30 PM

**Comment by KNGJOEL** [comment]
Yes, i will commit the blog page soon

Le mar. 10 août 2021 à 18:01, Rebecca Bilbro ***@***.***> a
écrit :

**Review by rebeccabilbro — CHANGES_REQUESTED** [review]
This is looking great @KNGJOEL! My only request on this PR is that we change the default language for the Chinese blog to English rather than French for the 3 blogposts. Once this is updated, I think we can go ahead and merge this PR!

**Comment by KNGJOEL** [comment]
> This is looking great @KNGJOEL! My only request on this PR is that we change the default language for the Chinese blog to English rather than French for the 3 blogposts. Once this is updated, I think we can go ahead and merge this PR!

Got it

**Review by rebeccabilbro — APPROVED** [review]

**Pull request merged**
