### PR TITLE
Bug fix for french page

### PR DESCRIPTION
**Pull request by KNGJOEL**

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
This looks great @KNGJOEL ! Do you think we could also update the tagline in `data/fr/banner.yml` so that it is a better approximation of the new English text?

Screen Shot 2021-08-09 at 1 57 40 PM
Screen Shot 2021-08-09 at 1 57 49 PM

**Comment by KNGJOEL** [comment]
No problem

**Comment by KNGJOEL** [comment]
It is Done

**Review by rebeccabilbro — APPROVED** [review]
Looks great, thank you so much @KNGJOEL

**Comment by KNGJOEL** [comment]
Don't Mention Ms.Rebecca

Le lun. 9 août 2021 à 16:41, Rebecca Bilbro ***@***.***> a
écrit :

**Pull request merged**
