### PR TITLE
updated style.css for our team height and width

### PR DESCRIPTION
**Pull request by KNGJOEL**

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Hey there @KNGJOEL &mdash; I just took a look and it seems like the change did not have an effect on the height of the blocks that contain the team images. Here is what the page looks like when I build your branch locally:

Screen Shot 2021-08-07 at 11 52 23 AM

As you can see above, the box containing Benjamin's picture and details is longer than the boxes for me and Edwin. Can you figure out how to get them all the same height, just like you did with the blog posts boxes (screen shot below):

Screen Shot 2021-08-07 at 11 55 06 AM

**Comment by KNGJOEL** [comment]
Hello Ms.Rebecca, got it, let me solve it

**Comment by KNGJOEL** [comment]
Screen Shot 2021-08-07 at 1 32 28 PM

**Comment by KNGJOEL** [comment]
I did check and I don't know were the problem is located because the same change is working locally.
Could you please try again to see if it will work ?

**Comment by rebeccabilbro** [comment]
Just checked and it still is not building correctly for me. I'm using Chrome in case that helps. Perhaps we can ask @bbengfort to build the branch locally and see if he gets the same result?

**Comment by KNGJOEL** [comment]
> Just checked and it still is not building correctly for me. I'm using Chrome in case that helps. Perhaps we can ask @bbengfort to build the branch locally and see if he gets the same result?

Hello Ms.rebecca, Just double check and it is working for me I also use chrome, I can't figure out what is happening. Yes maybe we should ask Mr.Benjamin

**Comment by bbengfort** [comment]
I took the following steps:

1. Checked out KNGJOEL/fix-our-impact-section
2. Ran `hugo serve -D` 

Here are the our team sections at various different browser resolutions (using Chrome):

Screen Shot 2021-08-09 at 10 10 13
Screen Shot 2021-08-09 at 10 10 31
Screen Shot 2021-08-09 at 10 10 38
Screen Shot 2021-08-09 at 10 10 45

**Comment by rebeccabilbro** [comment]
Fantastic, thank you both @KNGJOEL @bbengfort!

**Review by rebeccabilbro — APPROVED** [review]

**Pull request merged**
