### PR TITLE
Adds bg color to services quote

### PR DESCRIPTION
**Pull request by daniellemaxwell**
Scope of Changes:

- Adds bg color to quote on the services page
- Displays quote in the center of the page on larger screens

Fixes SC-21865

Acceptance Criteria:
https://www.awesomescreenshot.com/video/21375035?key=f2aa0c475df23de457b7d6a789eccebf

Here's a link to an alternative using a different color for the emphasis text: https://www.awesomescreenshot.com/image/43404833?key=18eeaf0432fa755c17870d4bde83768a

I tested colors from the palette provided in a previous PR comment. Many either had a low color contrast against the background (the bg color added in this PR or with white as the bg color). I tried a darker background color, but it didn't really pair well with the tone of the quote in my opinion. Some of the others appeared too dark and didn't really pop on the screen.

### CODE REVIEW

**Review by rebeccabilbro — COMMENTED** [review]
Thank you @daniellemaxwell! The light blue background looks good - can we try center-aligning the text of the quote to make it stand out more?
Screenshot 2023-10-06 at 10 09 12 AM





We should only use the "lapis lazuli" color for hyperlinked text because it is causing confusion for visitors to the page who expect to be able to click on blue text. 
Screenshot 2023-10-06 at 10 04 30 AM

It sounds like of the options available, we should use the orange and dark blue colors for emphasis, as shown in the alternate image you shared. 

Am I correct in assuming that if we change the emphasis colors for the quote in the services page it will also update the emphasis colors elsewhere on the page? 
eg here:
Screenshot 2023-10-06 at 10 02 18 AM

and here
Screenshot 2023-10-06 at 10 03 25 AM

Or do we need to open up follow-on stories to make sure the emphasis text gets updated there too?

**Comment by rebeccabilbro** [comment]
Also, another small thing (and feel free to do this as a separate story) - would you mind re-adding the Services link to the top nav? Since we're pushing hard on bizdev now, it will be good to make it as easy as possible for visitors to find!
Screenshot 2023-10-06 at 10 12 54 AM

**Comment by daniellemaxwell** [comment]
@rebeccabilbro Follow on stories will need to be created to change the color of the emphasis text on the site. The examples shown in the image provided are all wrapped in different types of elements (H1, span, etc.) and have the text color specified.

I'll add `Services` to the nav bar.

**Comment by daniellemaxwell** [comment]
@rebeccabilbro Here's a link to a screenshot of the changes: https://www.awesomescreenshot.com/image/43406859?key=61735685c5c568ac155e5be814d2dadc

**Review by rebeccabilbro — APPROVED** [review]
lgtm 😎

**Pull request merged**
